import type { Metadata } from "next";
import { Arrow } from "../../components/SiteShell";
import { PageHero, SectionHeader } from "../../components/ui";

export const metadata: Metadata = { title: "Servicios de Diseño Web | AHPixel Studio", description: "Landing pages, sitios empresariales, sitios profesionales y rediseños web estratégicos.", alternates: { canonical: "/es/services", languages: { "es-PE": "/es/services", "en-US": "/services" } } };
const offers = [
  { n:"01", title:"Landing Page", intro:"Una página enfocada y de alto impacto, creada alrededor de un objetivo claro.", ideal:"Campañas, servicios, lanzamientos y marcas personales.", includes:["Estrategia y estructura","Dirección visual personalizada","Desarrollo responsive","Flujo de contacto o conversión"] },
  { n:"02", title:"Sitio Empresarial", intro:"Una presencia multipágina confiable que explica el negocio con claridad.", ideal:"Empresas en crecimiento, negocios locales y proveedores de servicios.", includes:["Inicio, Nosotros, Servicios y Contacto","Páginas empresariales adicionales","Sistema de diseño responsive","Rutas claras de consulta"] },
  { n:"03", title:"Sitio Profesional", intro:"Una plataforma refinada que convierte experiencia en confianza.", ideal:"Abogados, clínicas, consultores, arquitectos y profesionales independientes.", includes:["Estructura enfocada en posicionamiento","Presentación de servicios","Identidad visual profesional","Contacto mobile-first"] },
  { n:"04", title:"Rediseño Web", intro:"Una reconstrucción estratégica para un sitio que ya no representa al negocio.", ideal:"Marcas establecidas con visuales, estructura o rendimiento desactualizados.", includes:["Refinamiento de identidad visual","Experiencia responsive","Navegación y estructura de contenido","Mejoras de rendimiento"] },
];
const process = [["01","Descubrir"],["02","Diseñar"],["03","Construir"],["04","Refinar"],["05","Publicar"]];
export default function ServicesPage() { return <main><PageHero eyebrow="Servicios / Lo que hacemos" title={<>Diseñamos.<br />Construimos.<br /><em>Tú creces.</em></>} intro="Sitios web claros y modernos diseñados para necesidades reales de negocio, sin complejidad innecesaria." /><section className="offers section-space light-section"><SectionHeader index="01" label="Servicios actuales" dark /><div className="offer-list">{offers.map(o=><article key={o.n} data-reveal><div className="offer-title"><span>{o.n}</span><h2>{o.title}</h2></div><div className="offer-info"><p>{o.intro}</p><small>Ideal para</small><p>{o.ideal}</p></div><ul>{o.includes.map(i=><li key={i}>{i}</li>)}</ul></article>)}</div></section><section className="services-process section-space"><SectionHeader index="02" label="Cómo avanza un proyecto" /><div className="section-title-row" data-reveal><h2>Un camino claro.<br /><em>Sin misterio.</em></h2><p>Cada fase tiene un propósito, una decisión y un resultado tangible.</p></div><div className="mini-process">{process.map(([n,t])=><div key={n} data-reveal><span>{n}</span><i/><strong>{t}</strong></div>)}</div></section><section className="service-note-section light-section"><span>Nota de alcance / 2026</span><h2 data-reveal>Enfocados en sitios web.<br /><em>E-commerce vendrá después.</em></h2><p data-reveal>Actualmente nos enfocamos en sitios de marketing, empresariales y profesionales de alta calidad.</p><a href="/es/contact" className="button button-dark" data-reveal>Conversemos sobre tu proyecto <Arrow /></a></section></main>; }
