import { Metadata } from "next";
import Image from "next/image";
import { projects } from "../../../data/site";
import { Arrow } from "../../../components/SiteShell";
import { SectionHeader } from "../../../components/ui";
import { CaseStudyMotion } from "../../../components/interactive/CaseStudyMotion";
import { TrackedLink } from "../../../components/TrackedLink";

const project = projects.find(item => item.slug === "lumen-dental-studio")!;

export const metadata: Metadata = { title: "LUMEN Dental Studio — Concepto Web de Salud | AHPixel Studio", description: "Un concepto web para una clínica dental moderna, enfocado en confianza, claridad y una experiencia digital más humana.", alternates: { canonical: "/es/work/lumen-dental-studio", languages: { "es-PE": "/es/work/lumen-dental-studio", "en-US": "/work/lumen-dental-studio" } }, openGraph: { title: "LUMEN Dental Studio — Concepto Web de Salud", description: "Proyecto conceptual ficticio de AHPixel Studio.", images: [{ url: "/projects/lumen/desktop-hero.webp", width: 1536, height: 1024, alt: "Concepto web de LUMEN Dental Studio" }] }, twitter: { card: "summary_large_image", title: "LUMEN Dental Studio — AHPixel Studio", description: "Concepto web moderno para salud dental.", images: ["/projects/lumen/desktop-hero.webp"] } };

export default function LumenCaseStudyEs() { return <main className="case-study lumen-case" style={{ "--case-accent": project.accent } as React.CSSProperties}><CaseStudyMotion />
  <section className="case-hero"><div className="case-no">Proyecto / {project.number}</div><p className="eyebrow" data-reveal><span />Proyecto conceptual · {project.year}</p><h1 data-reveal>Lumen<br /><em>Dental Studio</em></h1><p className="case-lead" data-reveal>Un concepto web para una clínica dental moderna, enfocado en confianza, claridad y una experiencia digital más humana.</p><div className="case-actions" data-reveal>{project.liveUrl&&<TrackedLink eventName="live_demo_clicked" eventDetail={{project:project.slug,source:"case_study_top_es"}} className="button button-primary" href={project.liveUrl} target="_blank" rel="noopener noreferrer">Ver sitio web <Arrow /></TrackedLink>}<a className="button button-quiet" href="/es/work">Volver a proyectos <Arrow /></a></div></section>
  <section className="case-meta light-section"><div><span>Tipo de proyecto</span><strong>Sitio conceptual</strong></div><div><span>Industria</span><strong>Dental / Salud</strong></div><div><span>Servicios</span><strong>Diseño Web / Responsive / Desarrollo Frontend</strong></div><div><span>Año</span><strong>{project.year}</strong></div></section>
  <section className="case-overview section-space"><SectionHeader index="01" label="Descripción general" /><div className="case-copy"><h2 data-reveal>Salud sin<br /><em>frialdad clínica.</em></h2><p data-reveal>LUMEN explora cómo una clínica dental moderna puede transmitir confianza profesional y, al mismo tiempo, hacer que cada punto de contacto digital se sienta más humano. La experiencia ofrece información clara, un lenguaje visual sereno y un camino sencillo hacia la reserva.</p></div></section>
  <section className="case-image-wide" data-reveal><Image src={project.desktopImages[0]} alt="Inicio de LUMEN Dental Studio en escritorio" width={1440} height={1000} sizes="90vw" /><span>Escritorio / Inicio</span></section>
  <section className="case-direction section-space light-section"><SectionHeader index="02" label="Dirección visual" dark /><div className="direction-grid"><h2 data-reveal>Luminosa.<br />Serena.<br /><em>Humana.</em></h2><div data-reveal><p>El sistema visual combina blanco cálido, verde azulado suave y tipografía serif editorial para sentirse confiable, cuidado y distinto.</p><ul><li>Claridad clínica sin códigos visuales estériles</li><li>Fotografía arquitectónica y natural</li><li>Ritmo de lectura cómodo</li><li>Lenguaje centrado en el paciente</li></ul></div></div></section>
  <section className="case-desktop section-space"><SectionHeader index="03" label="Experiencia desktop" /><div className="case-copy"><h2 data-reveal>Información que se siente<br /><em>fácil de abordar.</em></h2><p data-reveal>La experiencia equilibra una primera impresión emocional con tratamientos, señales de confianza y acceso directo a la cita.</p></div><div className="desktop-frame" data-reveal><div className="frame-bar"><i/><i/><i/><span>LUMEN / TRATAMIENTOS</span></div><Image src={project.desktopImages[1]} alt="Arquitectura de tratamientos de LUMEN" width={1440} height={1000} sizes="(max-width:860px) 92vw,84vw" /></div></section>
  <section className="case-mobile light-section"><div className="case-mobile-copy"><SectionHeader index="04" label="Experiencia móvil" dark /><h2 data-reveal>Confianza que<br /><em>te acompaña.</em></h2><p data-reveal>La tipografía, los controles y el contenido móvil se recomponen para una lectura cómoda sin perder claridad ni identidad.</p></div><div className="phone-pair" data-reveal><div><Image src={project.mobileImages[0]} alt="Inicio móvil de LUMEN" width={390} height={844} sizes="(max-width:860px) 42vw,16vw" /></div><div><Image src={project.mobileImages[1]} alt="Tratamientos móviles de LUMEN" width={390} height={844} sizes="(max-width:860px) 42vw,16vw" /></div></div></section>
  <section className="case-details section-space"><SectionHeader index="05" label="Tratamientos / Arquitectura de información" /><div className="detail-grid">{[["01","Tratamientos claros","Los servicios se organizan según necesidades reales del paciente."],["02","Tipografía editorial","Una serif cálida da carácter y la sans-serif mantiene precisión."],["03","Confianza visual","El espacio, la fotografía y el lenguaje reducen fricción."],["04","Jerarquía responsive","La composición móvil se adapta, no solo se reduce."],["05","Camino del paciente","Las llamadas a la acción orientan sin presionar."],["06","Experiencia bilingüe","El contenido en español e inglés amplía el alcance."]].map(([n,t,p])=><article key={n} data-reveal><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
  <section className="case-result light-section"><SectionHeader index="06" label="Resultado final" dark /><h2 data-reveal>Una experiencia de salud<br /><em>construida desde la claridad.</em></h2><p data-reveal>El concepto final se siente profesional, sereno y útil desde la primera impresión hasta la solicitud de cita.</p><div className="concept-disclaimer" data-reveal><span>Nota importante</span><p>LUMEN Dental Studio es un proyecto conceptual ficticio creado para el portafolio de AHPixel Studio. No se presenta como cliente real ni como clínica existente.</p></div>{project.liveUrl&&<TrackedLink eventName="live_demo_clicked" eventDetail={{project:project.slug,source:"case_study_bottom_es"}} className="button button-dark" href={project.liveUrl} target="_blank" rel="noopener noreferrer">Ver sitio web <Arrow /></TrackedLink>}</section>
</main>; }
