"use client";

import Image from "next/image";
import { PointerEvent, useRef } from "react";
import { Project } from "../data/site";
import { Arrow } from "./SiteShell";
import { TrackedLink } from "./TrackedLink";

export function ProjectPreview({project}:{project:Project}){
  const stage=useRef<HTMLAnchorElement>(null);
  const move=(event:PointerEvent<HTMLAnchorElement>)=>{if(!stage.current||matchMedia("(pointer: coarse), (prefers-reduced-motion: reduce)").matches)return;const r=stage.current.getBoundingClientRect(),x=((event.clientX-r.left)/r.width-.5)*10,y=((event.clientY-r.top)/r.height-.5)*8;stage.current.style.setProperty("--preview-x",`${x}px`);stage.current.style.setProperty("--preview-y",`${y}px`);stage.current.style.setProperty("--phone-x",`${x*-.45}px`);stage.current.style.setProperty("--phone-y",`${y*-.7}px`)};
  const reset=()=>{stage.current?.style.setProperty("--preview-x","0px");stage.current?.style.setProperty("--preview-y","0px");stage.current?.style.setProperty("--phone-x","0px");stage.current?.style.setProperty("--phone-y","0px")};
  return <article className="project-showcase interactive-project-row" style={{"--project-accent":project.accent} as React.CSSProperties}><div className="project-info"><div className="project-topline"><span>{project.number}</span><small>{project.conceptProject?"Concept project":project.projectType}</small><small>{project.year}</small></div><h3>{project.title}</h3><ul>{project.services.map(service=><li key={service}>{service}</li>)}</ul><p>{project.description}</p><div className="project-actions"><TrackedLink eventName="case_study_clicked" eventDetail={{project:project.slug,source:"project_preview"}} className="button button-secondary" href={`/work/${project.slug}`}>View case study <Arrow/></TrackedLink>{project.liveUrl&&<TrackedLink eventName="live_demo_clicked" eventDetail={{project:project.slug,source:"project_preview"}} className="text-link" href={project.liveUrl} target="_blank" rel="noopener noreferrer">Live demo <Arrow/></TrackedLink>}</div></div><TrackedLink eventName="case_study_clicked" eventDetail={{project:project.slug,source:"project_stage"}} ref={stage} href={`/work/${project.slug}`} className="project-stage" aria-label={`View ${project.title} case study`} onPointerMove={move} onPointerLeave={reset}><span className="stage-note">Responsive presentation / {project.number}</span><div className="project-browser"><div className="browser-bar"><i/><i/><i/><span>{project.title.split(" ")[0].toUpperCase()} / DESKTOP</span></div><Image src={project.desktopImages[0]} alt={`${project.title} desktop website homepage`} width={1425} height={990} sizes="(max-width:860px) 88vw,58vw"/></div><div className="project-phone"><Image src={project.mobileImages[0]} alt={`${project.title} mobile website homepage`} width={375} height={812} sizes="(max-width:860px) 30vw,12vw"/></div><span className="project-view">View project <Arrow/></span><span className="project-pointer">View project ↗</span></TrackedLink></article>;
}
